### PR TITLE
Improve security

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Easier for you to review and merge: https://github.com/MattJeanes/Joystick-Module/pull/49/files?diff=unified&w=1

**Comment by dvdvideo1234** [comment]
Please merge after my friend tests it in his server

**Comment by MattJeanes** [comment]
Looks pretty reasonable to me, what security is being improved here exactly?

**Comment by dvdvideo1234** [comment]
My friend is a server owner and he is concerned string find does not use safe patterns ( containing special characters ), so I optimized UID validation. The library method `jcon.isValidUID` now uses:
1. Iinteger for loop with local reference when validating the UID
2. Pre-defined table with banned UID patterns ( they do not contain special symbols )
3. Add Forced validation character set so it can be used in the tool without mess up the serialization

**Comment by MattJeanes** [comment]
Okay, sounds good to me! Let me know when your friend has finished testing it, I'll take your word for it

**Comment by MattJeanes** [comment]
Also liking the conversion from tabs -> spaces, nice!

**Review by MattJeanes — APPROVED** [review]

**Comment by dvdvideo1234** [comment]
Made my personal primary test:
image

**Comment by dvdvideo1234** [comment]
@MattJeanes

image

Ok with me whenever you are ready ;)

**Pull request merged**
